version: "3.9"

services:
  db:
    image: postgres:18-alpine
    container_name: app-db
    environment:
      POSTGRES_DB: application_data
      POSTGRES_USER: job_searcher
      POSTGRES_PASSWORD: 231198
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U job_searcher -d application_data"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/tobin123456/application-tracker-backend:1.0
    container_name: app-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/application_data
      SPRING_DATASOURCE_USERNAME: job_searcher
      SPRING_DATASOURCE_PASSWORD: 231198
      CORS_ALLOWED_ORIGINS: http://localhost:4200
      JWT_SECRET_KEY: MySuperSecretKeyForJWTsThe_Factory_Must_Grow!
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ghcr.io/tobin123456/application-tracker-frontend:1.0
    container_name: app-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db-data: